version: '3.3'
services:
  drupal:
    image: bitnami/drupal:latest
    volumes:
      - drupal_data:/bitnami/drupal
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_NAME=final
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD=<Sizin Öğrenci Numaranız>
      - DRUPAL_PASSWORD=adminpassword
  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=final
      - MARIADB_USER=YAM428
      - MARIADB_PASSWORD=<Sizin Öğrenci Numaranız>
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - drupal_data:/bitnami/drupal

volumes:
  drupal_data:
  mariadb_data:
